import type React from "react";
import { motion } from "framer-motion";
import { ContextData } from "../../config/context";
import { SEOData } from "../../type";
import SEO from "../Helmet/helment";
import { useContext } from "react";

const PrivacyPolicyPage: React.FC = () => {
  const { seo } = useContext(ContextData) as { seo: SEOData };

  // Animation variants
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.3,
      },
    },
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        duration: 0.6,
        ease: "easeOut",
      },
    },
  };

  return (
    <>
      <SEO seo={seo} />
      <div className="relative overflow-hidden bg-gray-50 min-h-screen">
        {/* Background decorative elements */}
        <div className="absolute inset-0 overflow-hidden opacity-10">
          <div className="absolute top-20 left-10 w-64 h-64 rounded-full bg-[#b7603d] mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
          <div className="absolute bottom-1/4 right-20 w-72 h-72 rounded-full bg-[#b7603d] mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-3000"></div>
          <div className="absolute top-1/3 left-1/2 w-60 h-60 rounded-full bg-[#b7603d] mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-6000"></div>
        </div>

        {/* Diagonal accent shapes */}
        <div className="absolute top-0 right-0 w-64 h-64 -mr-32 -mt-32 bg-[#b7603d]/10 transform rotate-45 rounded-lg"></div>
        <div className="absolute bottom-0 left-0 w-64 h-64 -ml-32 -mb-32 bg-[#b7603d]/10 transform rotate-45 rounded-lg"></div>

        <main className="relative max-w-5xl mx-auto px-4 sm:px-10 md:px-16 lg:px-20 xl:px-24 pb-10 md:pb-24 pt-16">
          {/* Animated header */}
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="mb-12 text-center"
          >
            <h1 className="text-4xl font-bold mb-4 text-gray-900">Privacy Policy</h1>
            <div className="w-32 h-1.5 bg-[#b7603d] mx-auto rounded-full"></div>
            <p className="mt-4 text-gray-600 max-w-2xl mx-auto">
              Effective Date: 2 August 2025
            </p>
            <p className="text-gray-500 text-sm">
              Brand: 7UniqueVerify, a brand of Sevenunique Tech Solutions Pvt. Ltd.

            </p>
          </motion.div>

          {/* Policy content with staggered animations */}
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="prose prose-lg max-w-none bg-white/90 backdrop-blur-sm rounded-2xl shadow-xl p-8 sm:p-10 border border-gray-100"
          >
            <div className="space-y-8 text-gray-700">
              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  1. Introduction
                </h2>
                <p>
                  This Privacy Policy is published in accordance with the Information Technology Act, 2000 and applicable data protection rules in India. It is an electronic record generated by a computer system and does not require any physical or digital signature.
                </p>
                <p>
                  <strong>Sevenunique Tech Solutions Pvt. Ltd.</strong>, a company incorporated under Indian law, owns and operates the website <a href="https://www.7uniqueverfiy.com" className="text-[#b7603d] font-medium  hover:text-[#9a4f32] transition-colors">https://www.7uniqueverfiy.com</a> under the brand <strong>7UniqueVerify</strong>. Our registered office is located at Plot No. 97, Dakshinpuri-I, Shrikishan, Sanganer, Jagatpura, Jaipur, Rajasthan – 302017, India.
                </p>
                <p>
                  We are committed to protecting your privacy and handling your personal data responsibly and transparently. This policy outlines how we collect, use, disclose, and protect your data while delivering verification and compliance services.
                </p>
                <p>
                  By accessing our website, using our APIs, or engaging with our dashboard, you agree to the terms outlined in this Privacy Policy.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  2. Commitment to Your Privacy
                </h2>
                <p>
                  At 7UniqueVerify, your trust is our highest priority. We are fully committed to ensuring the privacy and security of the information you share with us. We understand the sensitivity of the data handled through our verification services and treat it with utmost care and responsibility.
                </p>
                <p>
                  We strictly adhere to a no-sale, no-rent policy regarding your personal or business data. Your information will never be misused or shared with unauthorized parties without your explicit consent. We only process your data for legitimate, lawful purposes that directly support our service delivery, compliance, or platform improvements.
                </p>
                <p>
                  Our data handling processes are guided by transparency. We make it clear what data we collect, why we collect it, and how it is processed. Whether you're using our APIs, dashboard, or website, you can expect full accountability and clarity in our data protection practices.
                </p>
                <p>
                  Your privacy is not just a policy—it's a principle we uphold in every interaction.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  3. Services Covered
                </h2>
                <p>
                  <strong>7UniqueVerify</strong>, a product of <strong>Sevenunique Tech Solutions Pvt. Ltd.</strong>, offers a diverse range of over 84 verification and compliance APIs tailored to meet the needs of businesses, financial institutions, fintech startups, and government agencies. Our platform ensures seamless integration of real-time verification services through both direct API integration and a secure, user-friendly web dashboard.
                </p>
                <p>
                  Our<strong> KYC and Identity Verification APIs</strong> include Aadhaar (Offline XML, eKYC, VID-based), PAN verification, Passport checks, Voter ID, and Driving License (DL v1 & v2) validations. These APIs help businesses onboard users swiftly and in compliance with regulatory standards.
                </p>
                <p>
                  Our <strong>Banking Verification APIs</strong> cover Penny Drop verification, Pennyless verification, hybrid bank account checks, and IFSC code validation. These tools assist in secure fund transfers and fraud prevention.
                </p>
                <p>
                  Under <strong>Compliance APIs</strong>, we support GSTIN verification, EPFO/UAN lookups, FSSAI registration checks, and IEC (Import Export Code) validation—critical for organizations operating within regulatory frameworks.
                </p>
                <p>
                  <strong>Vehicle and Transport APIs</strong> include RC verification and driving license checks, useful for auto-finance, insurance, and ride-sharing companies.
                </p>
                <p>
                  For identity assurance, we offer<strong> Biometric & AI-based Verification services</strong> like Face Match and Liveness Detection, which are crucial for fraud mitigation and remote KYC workflows.
                </p>
                <p>
                  We also support <strong>DigiLocker API Integration</strong>, allowing users to fetch government-issued documents securely with consent. Additionally, we offer <strong>Crime and Background Check APIs</strong> for pre-employment screening, tenant checks, and sensitive onboarding.
                </p>
                <p>
                  These services are accessible through:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Direct API Integration:</strong> ideal for platforms with in-house developers, using secure endpoints and access tokens.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Secure Web Dashboard:</strong> designed for operational teams to manually verify data without needing any coding knowledge.</span>
                  </li>
                </ul>
                <p>
                  Together, our services deliver scalable, compliant, and secure verification solutions for organizations of all sizes and industries.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  4. Information We Collect
                </h2>
                <p>
                  At <strong>7UniqueVerify</strong>, a brand of <strong>Sevenunique Tech Solutions Pvt. Ltd.</strong>, we provide API-based digital verification services to third-party platforms such as websites, mobile apps, ERPs, and CRMs operated by our clients. These services are not offered directly to consumers on our website, but rather through APIs that clients integrate into their own platforms. Accordingly, we collect two primary types of data: (1) Client business information and (2) End-user verification data transmitted via API.
                </p>
                <p><strong>From Clients (Business Partners/Integrators):</strong></p>
                <p>
                  When businesses register to use our verification APIs, we collect:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Company name, authorized contact person, email ID, and mobile number</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>GSTIN, PAN, business registration documents, and address details</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Login metadata such as IP address, browser/device type</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Uploaded documents for KYC and compliance</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>API usage logs, integration metadata, and technical support communication</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Payment records, invoice history, and plan details</span>
                  </li>
                </ul>
                <p>
                  This data is used to create secure API keys, monitor fair use, and ensure legal and regulatory compliance.
                </p>
                <p><strong>From End-Users (Whose Data is Verified via Client Platforms):</strong></p>
                <p>
                  When a client uses our APIs within their own website/app, they initiate secure API calls to verify their customers. The following data is processed via our APIs:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Aadhaar (masked/tokenized), PAN, passport, Voter ID, DL</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Bank account number with IFSC for penny drop or account matching</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>EPFO/UAN, vehicle RC, and similar identifiers</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Facial images for face match and liveness detection</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Geo-location, device/IP info at time of verification</span>
                  </li>
                </ul>
                <p>
                  We do <strong>not collect this data directly</strong>. Clients are responsible for obtaining valid user consent before sending any data to our APIs. All data is encrypted in transit and handled as per Indian data privacy laws.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  5. How We Use Your Information
                </h2>
                <p>
                  At <strong>7UniqueVerify</strong>, we process both client and end-user data exclusively to facilitate secure identity verification and regulatory compliance through our APIs and platform. The information we collect is used in accordance with applicable Indian data protection laws and contractual obligations.
                </p>
                <p><strong>For Clients (Businesses Using Our APIs):</strong></p>
                <p>
                  Client-provided business and integration information is used to:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Set up and authenticate access to our API services</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Generate API keys and configure usage settings</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Deliver API responses on our secure dashboard or via direct integration</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Monitor usage patterns, detect anomalies or abuse, and ensure compliance with fair use policies</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Generate invoices, process payments, and maintain transaction logs</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Provide technical support, respond to tickets, and improve API documentation or dashboard UX</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Send important communications such as API version changes, maintenance schedules, security advisories, and service enhancements</span>
                  </li>
                </ul>
                <p>
                  We also use client data for internal analytics to optimize system performance, service stability, and resource allocation.
                </p>
                <p><strong>For End-User Data (Processed via Client API Calls):</strong></p>
                <p>
                  The personal data of end-users—submitted by clients through API calls—is used <strong>solely to perform the requested verification checks</strong>. For example:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Aadhaar, PAN, Voter ID, DL, etc., are validated via authorized sources</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Bank account info is verified using penny drop or account match APIs</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Facial images are matched using AI-based face recognition and liveness detection</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>UAN/EPFO, GST, and other identifiers are verified against official registries</span>
                  </li>
                </ul>
                <p>
                  We do <strong>not use, repurpose, or share</strong> end-user data beyond what is required to complete the verification process. It is not stored longer than needed and is never sold or disclosed without legal or contractual basis.
                </p>
                <p>
                  All usage is governed by secure API protocols, encryption standards, and access controls.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  6. Legal Basis for Processing
                </h2>
                <p>
                  7UniqueVerify processes personal and business data in strict compliance with applicable Indian data protection regulations. The following legal bases govern our data handling practices:
                </p>
                <p><strong>1. User Consent</strong></p>
                <p>
                  We process personal data only when we have the appropriate consent:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Explicit consent</strong> is obtained by clients from their end-users before initiating any verification through our APIs.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Implied consent</strong> applies when clients willingly register, integrate, or utilize our platform and services, acknowledging the terms outlined in our Privacy Policy and Terms of Service.</span>
                  </li>
                </ul>
                <p><strong>2. Contractual Necessity</strong></p>
                <p>
                  Data provided by clients is processed as part of our contractual agreement to:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Enable secure identity verification services</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Deliver API responses</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Maintain account-related records, billing, and service performance</span>
                  </li>
                </ul>
                <p>
                  This processing is essential to fulfill our obligations as a service provider.
                </p>
                <p><strong>3. Legal and Regulatory Compliance</strong></p>
                <p>
                  We process and retain data where required by Indian laws, including but not limited to:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>The Aadhaar Act, 2016</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>RBI Master Directions on KYC</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>SEBI and other financial regulations for onboarding and verification</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>The Information Technology Act, 2000, and associated rules</span>
                  </li>
                </ul>
                <p>
                  We also comply with UIDAI guidelines, including consent architecture and masking/tokenization requirements for Aadhaar.
                </p>
                <p><strong>4. Legitimate Interests</strong></p>
                <p>
                  We may process certain data to:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Prevent fraudulent activity or misuse of the platform</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Ensure the security, stability, and reliability of our APIs and dashboards</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Improve system performance and client support workflows</span>
                  </li>
                </ul>
                <p>
                  All data is handled with due care, applying appropriate technical and organizational safeguards to ensure confidentiality, integrity, and compliance.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  7. Data Storage & Retention
                </h2>
                <p>
                  At <strong>7UniqueVerify</strong>, we prioritize secure and lawful data management. All client and end-user data is handled in accordance with Indian regulations and industry best practices.
                </p>
                <p><strong>1. Secure Storage Infrastructure</strong></p>
                <p>
                  All data is stored on <strong>ISO 27001-certified servers</strong> located <strong>within India</strong>, ensuring adherence to the highest international standards for information security.
                </p>
                <p>
                  We apply end-to-end encryption protocols for both <strong>data in transit</strong> and <strong>data at rest</strong>, using technologies such as <strong>SSL/TLS</strong> and <strong>AES-256</strong> encryption.
                </p>
                <p><strong>2. Retention Policy</strong></p>
                <p>
                  <strong> Verification logs</strong> (API request/response metadata) are retained for a period of <strong>up to 180 days</strong> to comply with audit and regulatory requirements.
                </p>
                <p>
                  After this retention period, logs are <strong>securely deleted</strong> using automated, irreversible deletion protocols.
                </p>
                <p><strong>3. Sensitive Data Handling</strong></p>
                <p>
                  We do <strong>not store Aadhaar numbers, PAN details</strong>, or <strong>biometric images</strong> (e.g., facial scans used for liveness or face match) <strong>beyond the duration required to complete the verification task</strong>.
                </p>
                <p>
                  Storage of such data is strictly temporary and governed by compliance rules under:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>The <strong>Aadhaar Act, 2016</strong></span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>UIDAI</strong> circulars and API tokenization protocols</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Applicable <strong>RBI and SEBI KYC regulations</strong></span>
                  </li>
                </ul>
                <p><strong>4. Data Minimization</strong></p>
                <p>
                  We follow the principle of <strong>data minimization</strong>, collecting and storing only the information necessary to deliver our services.
                </p>
                <p>
                  By using our services, clients agree to manage end-user data responsibly and ensure that all data provided for verification has been collected lawfully with user consent.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  8. Disclosure of Information
                </h2>
                <p>
                  At <strong>7UniqueVerify</strong>, we are committed to maintaining the confidentiality and integrity of your data. We <strong>do not sell, trade, or rent</strong> any personal or verification-related data under any circumstances.
                </p>
                <p><strong>1. Lawful Disclosures Only</strong></p>
                <p>
                  We may disclose information solely under the following lawful and controlled circumstances:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Regulatory or Legal Obligations:</strong> We may disclose data to <strong>government bodies, law enforcement agencies, or regulatory authorities</strong> when required under applicable Indian laws (such as the IT Act, Aadhaar Act, or RBI/SEBI mandates), or upon receipt of a valid legal request.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>API Processing Partners:</strong> For successful identity and document verification, your data may be routed through <strong>authorized third-party data sources</strong> (such as UIDAI, NSDL, NPCI, GSTN, etc.). These interactions are performed in real time and only for the intended API request.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Internal Operations:</strong> Our internal teams (engineering, support, compliance) may access data only on a <strong>need-to-know basis</strong> for debugging, client servicing, or fraud investigation—always under strict <strong>role-based access control (RBAC)</strong>.</span>
                  </li>
                </ul>
                <p className="mt-4"><strong>2. Binding Confidentiality Obligations</strong></p>
                <p>
                  All third-party service providers and internal stakeholders are:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Bound by strict NDAs and contractual obligations</strong></span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Compliant with ISO/IEC 27001:2013 security standards</strong></span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>Required to <strong>implement data encryption, access controls, and audit logging</strong></span>
                  </li>
                </ul>
                <p>
                  We never disclose data beyond what is necessary to fulfill the verification request, and always in accordance with Indian data protection laws. Your trust is our priority, and every disclosure is justified, traceable, and compliant.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  9. Your Rights
                </h2>
                <p>
                  At <strong>7UniqueVerify</strong>, we respect your control over personal information. In accordance with applicable Indian laws (such as the Information Technology Act, 2000 and related rules), you have the following rights:
                </p>
                <p><strong>1. Right to Access and Review</strong></p>
                <p>
                  You may request access to any personal data we have processed through our platform or APIs on your behalf. We will provide a summary of the data processed, subject to verification of identity and scope of access.
                </p>
                <p><strong>2. Right to Rectify or Delete</strong></p>
                <p>
                  You can request correction of inaccurate or outdated information, or request deletion of data that is no longer necessary for the purpose it was collected—provided it's not legally required to be retained (e.g., regulatory logs).
                </p>
                <p><strong>3. Right to Withdraw Consent</strong></p>
                <p>
                  If you have previously given consent for data processing, you may withdraw it at any time where applicable. This may impact the availability or continuity of services (e.g., user identity cannot be verified post-withdrawal).
                </p>
                <p><strong>4. Right to Raise a Grievance</strong></p>
                <p>
                  If you believe your data has been misused, handled inaccurately, or processed without proper justification, you may submit a formal grievance. We are committed to resolving issues promptly and transparently.
                </p>
                <p><strong>5. How to Submit a Request</strong></p>
                <p>
                  All rights-based requests must be sent in writing to our <strong>Grievance Officer</strong>. Please include sufficient details to identify your relationship with our services (e.g., reference ID, integration client, date/time of request).
                </p>
                <p>
                  <strong> Contact Details</strong> are provided in Section 12 (Grievance Redressal).
                </p>
                <p>
                  We acknowledge all rights-based queries within <strong>48 hours</strong> and aim to resolve them within <strong>15 business days</strong>, in line with India's IT (Reasonable Security Practices and Procedures) Rules, 2011.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  10. Security Measures
                </h2>
                <p>
                  At <strong>7UniqueVerify</strong>, we are committed to maintaining the highest standards of data security to protect both client and end-user information processed through our platform. The following technical and organizational measures are implemented across all services:
                </p>
                <p><strong>Data Transmission</strong></p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>SSL/TLS Encryption:</strong> All communications between clients and our servers, including API requests and dashboard access, are protected using Secure Socket Layer (SSL) or Transport Layer Security (TLS) encryption.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Secure Authentication:</strong> API keys and session tokens are securely issued and validated to prevent unauthorized access.</span>
                  </li>
                </ul>
                <p><strong>Data at Rest</strong></p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>AES-256 Encryption:</strong> Sensitive data such as KYC documents and biometric inputs are encrypted using AES-256 standards when stored.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Limited Retention:</strong> Personally identifiable information (like Aadhaar, PAN, and biometric images) is not stored permanently unless legally required.</span>
                  </li>
                </ul>
                <p><strong>Access Control and Authorization</strong></p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Role-Based Access Control (RBAC):</strong> System access is restricted based on user roles to enforce the principle of least privilege.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Multi-Factor Authentication (MFA):</strong> Enabled for administrators and enterprise-level clients for enhanced security.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>IP Whitelisting:</strong> Available for enterprise clients to restrict platform access to approved IP addresses.</span>
                  </li>
                </ul>
                <p><strong>System Monitoring and Audits</strong></p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Vulnerability Assessments:</strong> Routine security scans and penetration tests are conducted to identify and fix vulnerabilities.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Audit Logs:</strong> All API activity and user interactions are logged and monitored for suspicious behavior or misuse.</span>
                  </li>
                </ul>
                <p><strong>Compliance</strong></p>
                <p>
                  Our infrastructure is hosted within India in ISO 27001-certified data centers. All data handling practices comply with Indian regulations, including IT Act requirements and UIDAI guidelines where applicable.
                </p>
                <p>
                  These measures are designed to protect your data from unauthorized access, breaches, or misuse while ensuring reliable and secure service delivery.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  11. Cookies & Tracking
                </h2>
                <p>
                  Our website uses cookies and similar tracking technologies to enhance user experience and ensure optimal performance. Cookies are small text files stored on your device by your browser when you visit our site.
                </p>
                <p>
                  We use cookies for the following purposes:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Session Management:</strong> To maintain secure login sessions and enable dashboard functionality.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Performance & Optimization:</strong> To track website performance and improve navigation.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span><strong>Usage Analytics:</strong> Tools like Google Analytics help us understand user behavior and site usage patterns to improve our services.</span>
                  </li>
                </ul>
                <p>
                  You can choose to disable cookies through your browser settings. However, please note that disabling certain cookies may affect the functionality of some features, including login, session continuity, and form submissions.
                </p>
                <p>
                  By continuing to use our website without modifying your cookie settings, you consent to our use of cookies as described in this section.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  12. Grievance Redressal
                </h2>
                <p>
                  If you have any concerns regarding the handling of your personal data or any aspect of this Privacy Policy, you may contact our designated Grievance Officer:
                </p>
                <p><strong>Grievance Officer:</strong> Mr. Deepak Sharma</p>
                <p><strong>Email:</strong> <a href="mailto:support@7unique.in" className="text-[#b7603d] font-medium  hover:text-[#9a4f32] transition-colors">✉️ support@7unique.in </a></p>
                <p><strong>Phone:</strong> 0141-4511098</p>
                <p><strong>Office Hours:</strong> Monday to Saturday, 10:00 AM – 6:00 PM IST</p>
                <p><strong>Head Office:</strong></p>
                <p>
                  Plot No. 97, Dakshinpuri‑I, Shrikishan, Sanganer, Jagatpura,<br />
                  Jaipur, Rajasthan – 302017, India
                </p>
                <p><strong>Corporate Office:</strong></p>
                <p>
                  Office No. 101/2, Vakratunda Corporate Park,<br />
                  Off Aarey Road, Goregaon (East),<br />
                  Mumbai – 400063, Maharashtra, India
                </p>
                <p>
                  All complaints will be acknowledged within 48 hours and resolved within 15 working days, in accordance with the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  13. Cross‑Border Transfers
                </h2>
                <p>
                  We are committed to maintaining data sovereignty and do not transfer personal data outside the territory of India unless:
                </p>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>The client explicitly authorizes such a transfer in writing, and</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-[#b7603d] mt-2 mr-2"></span>
                    <span>The transfer is required by applicable law, regulatory mandate, or court order, in which case it will be conducted with appropriate safeguards and prior notice.</span>
                  </li>
                </ul>
                <p>
                  All data storage and processing are conducted within secure, compliant environments located in India, unless otherwise contractually agreed or legally mandated.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  14. Children's Privacy
                </h2>
                <p>
                  At <strong>7UniqueVerify</strong>, we are committed to protecting the privacy of individuals, including minors. Our services—including API integrations and verification tools—are strictly intended for use by businesses, regulated entities, and authorized users aged 18 years and above. We do not knowingly offer our services to, or collect any personal information from, individuals under the age of 18.
                </p>
                <p>
                  If you are a parent or legal guardian and believe that your child has provided personal data through our platform, dashboard, or APIs, please contact us immediately. Upon verification, we will take prompt steps to remove the information and ensure it is not further processed, except as required by law.
                </p>
                <p>
                  Clients integrating our APIs into their websites or applications are solely responsible for ensuring age-appropriate use and consent mechanisms. By using our services, clients affirm that their use does not involve or target minors.
                </p>
                <p>
                  We do not process any verification requests involving minors unless required for lawful purposes and backed by explicit parental or legal guardian consent, along with applicable legal documentation. Any such processing will be reviewed on a case-by-case basis and will comply with Indian data protection and child safety regulations.
                </p>
                <p>
                  If we become aware of a violation of this policy, we will take immediate corrective action.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  15. Amendments to Policy
                </h2>
                <p>
                  <strong>7UniqueVerify</strong> reserves the right to amend, update, or revise this Privacy Policy at any time, in accordance with evolving legal, technological, or operational requirements. Any changes made to this policy will be posted on this page, along with a revised "Effective Date" at the top. In the event of significant updates—particularly those that materially affect how we handle your personal data—we may also provide direct notifications via email or dashboard alerts, where appropriate.
                </p>
                <p>
                  We strongly encourage users to review this policy periodically to stay informed about how we protect and use your data. Continued access to or use of our website, APIs, or services after changes have been published will be deemed as acceptance of the updated policy. If you do not agree with the revised terms, you should immediately discontinue use of our services.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  16. Governing Law & Jurisdiction
                </h2>
                <p>
                  This Privacy Policy is governed by the laws of the Republic of India. All matters relating to the interpretation, enforcement, or disputes arising from this policy or the use of our services shall fall under the exclusive jurisdiction of the competent courts located in Jaipur, Rajasthan.
                </p>
                <p>
                  By using our platform, you consent to submit to the jurisdiction of these courts and agree that all disputes will be resolved in accordance with applicable Indian laws, including the Information Technology Act, 2000, and other relevant regulations.
                </p>
              </motion.section>

              <motion.section variants={itemVariants}>
                <h2 className="text-xl font-semibold mb-4 text-[#b7603d] border-l-4 border-[#b7603d] pl-3 py-1">
                  17. Contact Information
                </h2>
                <p>
                  If you have any questions, concerns, or requests regarding this Privacy Policy or your data, you may  <a href="/contact-us" className="text-[#b7603d] font-medium underline hover:text-[#9a4f32] transition-colors">Contact Us</a>.
                </p>
                <p className="font-bold">
                  By accessing or using our website, APIs, or dashboard, you acknowledge that you have read and understood this Privacy Policy and consent to the collection, processing, and use of your data as outlined herein.
                </p>
              </motion.section>
            </div>
          </motion.div>
        </main>
      </div>
    </>
  );
};

export default PrivacyPolicyPage;